### ISSUE TITLE
BC break in 1.0.2 about initializing SDK client

### ISSUE THREAD

**Issue by andrew-demb** [DanteUkraine/playwright-graphql#11]
**Describe the bug**

In `1.0.1` to initialize the client with a custom GQL endpoint we should use the following statement:
```js
getSdkRequester(apiContext, '/graphql')
```

For `1.0.2` and `1.0.3` statement above doesn't work, but we need to change it to the following one:
```js
getSdkRequester(apiContext, { gqlEndpoint: '/graphql' })
```

**To Reproduce**

1. Install `1.0.1`
2. Initialize SDK with `getSdkRequester(apiContext, '/graphql')`
3. Update to the `1.0.2`
4. Send request and check whether request done for `/graphql`

**Expected behavior**

There are no BC breaks in patch releases OR they are documented in upgrade path recommendations.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by DanteUkraine** [comment]
I will fix it in version 1.0.4. Thanks you.
