### ISSUE TITLE
Logic about enabling raw response is broken - by default returned raw response instead of "data" payload key

### ISSUE THREAD

**Issue by andrew-demb** [DanteUkraine/playwright-graphql#12]
**Describe the bug**

The readme for `1.0.3` states, that raw response strategy is disabled by default, but it's not.

> Default values for options: { gqlEndpoint: '/api/graphql', rawResponse: false }

**To Reproduce**

```js
// raw response strategy is not enabled
const requester = getSdkRequester(apiContext, { gqlEndpoint: '/graphql' });
// ...

test('playwright-graphql test', {}, async ({ gql }) => {
  let login: string = process.env.VALID_EMAIL || '';
  let password: string = process.env.VALID_PASSWORD || '';
  const res = await gql.baseSdk.signIn({ signIn: { login, password } });

  expect(res).toHaveProperty('data'); // should fail - I didn't configure the requester to use raw responses
  console.log(res.data);
});
```

**Expected behavior**

Raw response strategy is disabled by default.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

Here's flipped logic in the requester: https://github.com/DanteUkraine/playwright-graphql/blob/7e325f6c6a840f6a03fd83c5ae4d85f023796c60/src/requester.ts#L32-L69.

It uses a raw response strategy when it is disabled in the config.

**Comment by DanteUkraine** [comment]
Thanks you for your findings. Nice job. I will review and merge your contribution ASAP.
