### ISSUE TITLE
status code in try/catch block 

### ISSUE THREAD

**Issue by Silentroze** [DanteUkraine/playwright-graphql#8]
Hi, please add the response.statusCode() in the try catch code. It will be better for logs
``` let json;
        try {
            json = await response.json();
        }
        catch (e) {
            throw new Error(`${e.message}
        \nResponse body is not a json but: ${await response.text()}
        \nHeaders: ${JSON.stringify(response.headers())}`);
        } -> 
         let json;
        try {
            json = await response.json();
        }
        catch (e) {
            throw new Error(`${e.message}
         \nResponse status is not a json but: ${await response.statusCode()}
        \nResponse body is not a json but: ${await response.text()}
        \nHeaders: ${JSON.stringify(response.headers())}`);
        }

**Comment by DanteUkraine** [comment]
> Hi, please add the response.statusCode() in the try catch code. It will be better for logs
> 
> ```
>         try {
>             json = await response.json();
>         }
>         catch (e) {
>             throw new Error(`${e.message}
>         \nResponse body is not a json but: ${await response.text()}
>         \nHeaders: ${JSON.stringify(response.headers())}`);
>         } -> 
>          let json;
>         try {
>             json = await response.json();
>         }
>         catch (e) {
>             throw new Error(`${e.message}
>          \nResponse status is not a json but: ${await response.statusCode()}
>         \nResponse body is not a json but: ${await response.text()}
>         \nHeaders: ${JSON.stringify(response.headers())}`);
>         }
> ```

Will do in 1.1.0

**Comment by DanteUkraine** [comment]
Fix is released.
