### ISSUE TITLE
Problem with second response.body iteration

### ISSUE THREAD

**Issue by Silentroze** [DanteUkraine/playwright-graphql#9]
When attempting to iterate over the response.body a second time, it returns nothing. The expected behavior is to reaccess the body contents to include them in the exception message. However, the body is empty during the second iteration, resulting in the exception message missing the response body details

**Comment by DanteUkraine** [comment]
> When attempting to iterate over the response.body a second time, it returns nothing. The expected behavior is to reaccess the body contents to include them in the exception message. However, the body is empty during the second iteration, resulting in the exception message missing the response body details

I was not able to reproduce. Please Provide more information or describe steps to reproduce.
<img width="957" alt="Screenshot 2024-11-26 at 17 29 31" src="https://github.com/user-attachments/assets/d8e9ab8e-ebbc-4de9-9236-12ceb4f2d55f">

**Comment by andrew-demb** [comment]
The issue was about failing to read the response body twice. 

This limitation is described also here https://github.com/whatwg/fetch/issues/196#issuecomment-171935172

But for now, I failed to reproduce the problem with Playwright.
